#!/usr/bin/env node
import { chmodSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";
import { loadWorkflowCommandSource } from "./workflow-command-skills.mjs";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const entries = [
  ["src/cli.ts", "scripts/cadre-cli.js", "cli"],
  ["src/cadre-core.ts", "scripts/cadre-core.js"],
  ["src/cadre-lsp-setup.ts", "scripts/cadre-lsp-setup.js"],
  ["src/cadre-lsp-review.ts", "scripts/cadre-lsp-review.js"],
  ["src/mcp/cadre-server.ts", "scripts/mcp/cadre-server.js", "embedded"]
];

const obsoleteOutputs = [
  "scripts/cadre-job-runner.js",
  "scripts/cadre-lsp-daemon.js",
  "scripts/mcp/cadre-server.external.js"
];

const banner = [
  "// AUTO-GENERATED by pnpm build from src/*.ts -- do not edit by hand.",
  "// Edit TypeScript sources under src/ instead."
].join("\n");

function walkFiles(dir, relativeDir = "") {
  const fullDir = path.join(repoRoot, dir, relativeDir);
  return readdirSync(fullDir, { withFileTypes: true }).flatMap((entry) => {
    const rel = path.join(relativeDir, entry.name).split(path.sep).join("/");
    const full = path.join(fullDir, entry.name);
    if (entry.isDirectory()) return walkFiles(dir, rel);
    return entry.isFile() ? [rel] : [];
  });
}

function collectTemplates() {
  const templates = {};
  for (const file of walkFiles("templates")) {
    const full = path.join(repoRoot, "templates", file);
    if (statSync(full).isFile()) templates[file] = readFileSync(full, "utf8");
  }
  return templates;
}

const embeddedAssets = {
  templates: collectTemplates()
};
const embeddedCommandSource = loadWorkflowCommandSource(repoRoot);

for (const outfile of obsoleteOutputs) {
  rmSync(path.join(repoRoot, outfile), { force: true });
}

for (const [, outfile] of entries) {
  mkdirSync(path.dirname(path.join(repoRoot, outfile)), { recursive: true });
}

await Promise.all(
  entries.map(([entry, outfile, assetMode]) => {
    let entryBanner = banner;
    if (assetMode === "embedded") {
      entryBanner = `${banner}\nconst __CADRE_EMBEDDED_ASSETS__ = ${JSON.stringify(embeddedAssets)};`;
    } else if (assetMode === "cli") {
      entryBanner = [
        banner,
        `const __CADRE_SKILL_SHIM__ = ${JSON.stringify(readFileSync(path.join(repoRoot, "skills/cadre/SKILL.md"), "utf8"))};`,
        `const __CADRE_COMMAND_SKILL_TEMPLATE__ = ${JSON.stringify(embeddedCommandSource.template)};`,
        `const __CADRE_WORKFLOW_COMMANDS__ = ${JSON.stringify(embeddedCommandSource.workflows)};`
      ].join("\n");
    }
    return (
    build({
      entryPoints: [path.join(repoRoot, entry)],
      outfile: path.join(repoRoot, outfile),
      bundle: true,
      platform: "node",
      target: "node18",
      format: "cjs",
      legalComments: "none",
      minify: false,
      banner: { js: entryBanner },
      logLevel: "silent"
    })
    );
  })
);

for (const [, outfile] of entries) {
  chmodSync(path.join(repoRoot, outfile), 0o755);
}

console.log(`Built ${entries.length} Cadre runtime bundles.`);
