#!/usr/bin/env node
import { chmodSync, mkdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const entries = [
  ["src/cadre-core.ts", "scripts/cadre-core.js"],
  ["src/cadre-job-runner.ts", "scripts/cadre-job-runner.js"],
  ["src/cadre-lsp-setup.ts", "scripts/cadre-lsp-setup.js"],
  ["src/cadre-lsp-review.ts", "scripts/cadre-lsp-review.js"],
  ["src/cadre-lsp-daemon.ts", "scripts/cadre-lsp-daemon.js"],
  ["src/mcp/cadre-server.ts", "scripts/mcp/cadre-server.js"]
];

const banner = [
  "// AUTO-GENERATED by pnpm build from src/*.ts -- do not edit by hand.",
  "// Edit TypeScript sources under src/ instead."
].join("\n");

for (const [, outfile] of entries) {
  mkdirSync(path.dirname(path.join(repoRoot, outfile)), { recursive: true });
}

await Promise.all(
  entries.map(([entry, outfile]) =>
    build({
      entryPoints: [path.join(repoRoot, entry)],
      outfile: path.join(repoRoot, outfile),
      bundle: true,
      platform: "node",
      target: "node18",
      format: "cjs",
      legalComments: "none",
      banner: { js: banner },
      logLevel: "silent"
    })
  )
);

for (const [, outfile] of entries) {
  chmodSync(path.join(repoRoot, outfile), 0o755);
}

console.log(`Built ${entries.length} Cadre runtime bundles.`);
