#!/usr/bin/env bash
#
# generate-skills.sh — Build the Claude and Codex plugin bundles from the
# master Cadre skill protocol sources.
#
# One source of truth is transformed into ignored local/install-time artifacts:
#   - Claude skill build artifact -> .claude/skills/cadre/SKILL.md
#   - Codex skill build artifact  -> .agents/skills/cadre/SKILL.md
#   - Claude plugin marketplace -> .claude-plugin/marketplace.json + plugins/cadre-claude/
#   - Codex plugin marketplace  -> .agents/plugins/marketplace.json + plugins/cadre/
#
# Edit the source skill in `skills/cadre/SKILL.md`, protocol sources in
# `skills/cadre/protocols/cadre-*.json`, reference masters in
# `scripts/agent-refs/`, templates in `templates/`, and runtime TypeScript in
# `src/`. Generated plugins are thin MCP entrypoints; the npm package owns the
# embedded `cadre-mcp` runtime. Runtime JavaScript under `scripts/` is built
# from `src/` by `pnpm build`. Plugin and marketplace outputs are generated on
# demand for source validation and `cadre install`; they are not source files.
#
# Usage:
#   pnpm generate
#   pnpm check
#   CADRE_SKIP_RUNTIME_BUILD=1 bash scripts/generate-skills.sh
#   CADRE_SKIP_RUNTIME_BUILD=1 CADRE_GENERATE_OUT=/tmp/cadre-gen bash scripts/generate-skills.sh
#   bash scripts/generate-skills.sh --check
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROOT_REPO="$(cd "$REPO_ROOT/.." && pwd)"
cd "$REPO_ROOT"

SOURCE_SKILL_FILE="skills/cadre/SKILL.md"
SOURCE_PROTOCOL_DIR="skills/cadre/protocols"

JSON_REFS=(
  "scripts/agent-refs/parallel-execution.json"
  "scripts/agent-refs/template-locator.json"
  "scripts/agent-refs/polyrepo-git.json"
  "scripts/agent-refs/cadre-sync.json"
  "scripts/agent-refs/ownership-guard.json"
  "scripts/agent-refs/mcp-contract.json"
  "scripts/agent-refs/provider-evidence.json"
  "scripts/agent-refs/team-ops.json"
)

TEMPLATES_SRC="templates"
CLAUDE_SKILL_DIR=".claude/skills/cadre"
CODEX_SKILL_DIR=".agents/skills/cadre"
CLAUDE_PLUGIN_DIR="plugins/cadre-claude"
CODEX_PLUGIN_DIR="plugins/cadre"
CLAUDE_PLUGIN_MARKETPLACE=".claude-plugin/marketplace.json"
CODEX_PLUGIN_MARKETPLACE=".agents/plugins/marketplace.json"
ROOT_CLAUDE_PLUGIN_MARKETPLACE=".claude-plugin/marketplace.json"
ROOT_CODEX_PLUGIN_MARKETPLACE=".agents/plugins/marketplace.json"

PLUGIN_NAME="cadre"
PLUGIN_VERSION="1.0.0"
PLUGIN_DESCRIPTION="MCP-first Cadre workflows using the global cadre-mcp runtime for context-driven development."
PLUGIN_AUTHOR_NAME="Vishal Kumar"
PLUGIN_AUTHOR_URL="https://github.com/vishal-kr-barnwal"
PLUGIN_HOMEPAGE="https://cadre-docs.pages.dev/"
PLUGIN_REPOSITORY="https://github.com/vishal-kr-barnwal/cadre"
PLUGIN_LICENSE="Apache-2.0"

CLAUDE_PROTOCOL_DIR="$CLAUDE_SKILL_DIR/protocols"
CODEX_PROTOCOL_DIR="$CODEX_SKILL_DIR/protocols"

MODE="${1:-generate}"
if [[ "${1:-}" == "--" && "${2:-}" == "--check" ]]; then
  MODE="--check"
fi
GEN_ROOT="${CADRE_GENERATE_OUT:-}"
CLEAN_GEN_ROOT=false
if [[ "$MODE" == "--check" ]]; then
  if [[ -z "$GEN_ROOT" ]]; then
    GEN_ROOT="$(mktemp -d)"
    CLEAN_GEN_ROOT=true
  fi
fi
if [[ -n "$GEN_ROOT" ]]; then
  mkdir -p "$GEN_ROOT"
fi
if [[ "$CLEAN_GEN_ROOT" == "true" ]]; then
  trap 'rm -rf "$GEN_ROOT"' EXIT
fi

out_path() {
  if [[ -n "$GEN_ROOT" ]]; then
    printf '%s/%s' "$GEN_ROOT" "$1"
  else
    printf '%s/%s' "$REPO_ROOT" "$1"
  fi
}

out_root_path() {
  if [[ -n "$GEN_ROOT" ]]; then
    printf '%s/root/%s' "$GEN_ROOT" "$1"
  else
    printf '%s/%s' "$ROOT_REPO" "$1"
  fi
}

extract_body() {
  awk '
    BEGIN { in_fm = 0; started = 0; seen = 0 }
    NR == 1 && $0 == "---" { in_fm = 1; seen = 1; next }
    in_fm == 1 && $0 == "---" { in_fm = 0; started = 1; next }
    in_fm == 1 { next }
    {
      if (seen == 0) started = 1
      if (started == 1) {
        if (printing == 0 && $0 ~ /^[[:space:]]*$/) next
        printing = 1
        print
      }
    }
  ' "$1"
}

extract_description() {
  awk '
    NR == 1 && $0 == "---" { in_fm = 1; next }
    in_fm == 1 && /^description:/ {
      sub(/^description:[[:space:]]*/, "")
      gsub(/^"|"$/, "")
      print
      exit
    }
    in_fm == 1 && $0 == "---" { exit }
  ' "$1"
}

write_file() {
  local path="$1"
  mkdir -p "$(dirname "$path")"
  cat > "$path"
}

copy_tree_with_links() {
  local source="$1" dest="$2" dir file rel
  rm -rf "$dest"
  mkdir -p "$dest"
  while IFS= read -r -d '' dir; do
    rel="${dir#"$source"/}"
    [[ "$rel" == "$dir" ]] && rel=""
    mkdir -p "$dest/$rel"
  done < <(find "$source" -type d -print0)
  while IFS= read -r -d '' file; do
    rel="${file#"$source"/}"
    mkdir -p "$(dirname "$dest/$rel")"
    if ! ln "$file" "$dest/$rel" 2>/dev/null; then
      cp -p "$file" "$dest/$rel"
    fi
  done < <(find "$source" -type f -print0)
}

SKILL_MARKER="AUTO-GENERATED by scripts/generate-skills.sh from skills/cadre/SKILL.md -- do not edit by hand."
PLUGIN_MARKER="AUTO-GENERATED by scripts/generate-skills.sh — edit the generator or source skill instead."

generate_skill() {
  local dest_dir="$1"
  rm -rf "$(out_path "$dest_dir")"
  mkdir -p "$(out_path "$dest_dir")"
  awk -v marker="<!-- $SKILL_MARKER -->" '
    NR == 1 && $0 == "---" { in_fm = 1; print; next }
    in_fm == 1 && $0 == "---" {
      print
      print ""
      print marker
      in_fm = 0
      next
    }
    { print }
  ' "$SOURCE_SKILL_FILE" | write_file "$(out_path "$dest_dir/SKILL.md")"
}

generate_protocols() {
  local platform="$1" dest_dir="$2" src name
  rm -rf "$(out_path "$dest_dir")"
  mkdir -p "$(out_path "$dest_dir")"

  for src in "$SOURCE_PROTOCOL_DIR"/cadre-*.json; do
    name="$(basename "$src" .json)"
    cp -p "$src" "$(out_path "$dest_dir/$name.json")"
  done
}

slice_ref() {
  awk -v keep="$2" '
    /<!-- \/AGENT:/ { inblock = 0; next }
    /<!-- AGENT:/   { line = $0; sub(/.*AGENT:/, "", line); sub(/[^a-z].*/, "", line); cur = line; inblock = 1; next }
    inblock == 1 && cur != keep { next }
    { print }
  ' "$1"
}

copy_skill_tree() {
  local src="$1" dest="$2" source_path
  rm -rf "$(out_path "$dest")"
  mkdir -p "$(dirname "$(out_path "$dest")")"
  if [[ -n "$GEN_ROOT" && -d "$GEN_ROOT/$src" ]]; then
    source_path="$GEN_ROOT/$src"
  else
    source_path="$REPO_ROOT/$src"
  fi
  copy_tree_with_links "$source_path" "$(out_path "$dest")"
}

build_runtime() {
  if [[ "${CADRE_SKIP_RUNTIME_BUILD:-}" == "1" || "$MODE" == "--check" ]]; then
    return
  fi
  if ! command -v pnpm >/dev/null 2>&1; then
    echo "error: pnpm is required to build Cadre runtime bundles from src/" >&2
    exit 1
  fi
  pnpm -s build:runtime
}

plugin_manifest_json() {
  local platform="$1"
  case "$platform" in
    codex)
      cat <<JSON
{
  "name": "$PLUGIN_NAME",
  "version": "$PLUGIN_VERSION",
  "description": "$PLUGIN_DESCRIPTION",
  "author": {
    "name": "$PLUGIN_AUTHOR_NAME",
    "url": "$PLUGIN_AUTHOR_URL"
  },
  "homepage": "$PLUGIN_HOMEPAGE",
  "repository": "$PLUGIN_REPOSITORY",
  "license": "$PLUGIN_LICENSE",
  "keywords": [
    "cadre",
    "context-driven-development",
    "skills",
    "mcp"
  ],
  "skills": "./skills/",
  "mcpServers": "./.mcp.json",
  "interface": {
    "displayName": "Cadre",
    "shortDescription": "Skill-first planning, tracks, reviews, and MCP tools.",
    "longDescription": "Cadre packages context-driven development workflows for Codex: setup, newtrack, implement, review, ship, land, archive, release, status, validation, and handoff.",
    "developerName": "$PLUGIN_AUTHOR_NAME",
    "category": "Productivity",
    "capabilities": [
      "Read",
      "Write",
      "Interactive"
    ],
    "defaultPrompt": [
      "Set up this repo with Cadre.",
      "Show Cadre team status.",
      "Review the current Cadre track."
    ],
    "brandColor": "#10A37F"
  }
}
JSON
      ;;
    claude)
      cat <<JSON
{
  "name": "$PLUGIN_NAME",
  "displayName": "Cadre",
  "version": "$PLUGIN_VERSION",
  "description": "$PLUGIN_DESCRIPTION",
  "author": {
    "name": "$PLUGIN_AUTHOR_NAME",
    "url": "$PLUGIN_AUTHOR_URL"
  },
  "homepage": "$PLUGIN_HOMEPAGE",
  "repository": "$PLUGIN_REPOSITORY",
  "license": "$PLUGIN_LICENSE",
  "keywords": [
    "cadre",
    "context-driven-development",
    "skills",
    "mcp"
  ],
  "skills": "./skills/",
  "mcpServers": "./mcp-config.json"
}
JSON
      ;;
  esac
}

write_plugin_manifest() {
  local platform="$1" plugin_dir="$2" manifest_dir
  case "$platform" in
    codex) manifest_dir="$(out_path "$plugin_dir/.codex-plugin")" ;;
    claude) manifest_dir="$(out_path "$plugin_dir/.claude-plugin")" ;;
  esac
  mkdir -p "$manifest_dir"
  plugin_manifest_json "$platform" > "$manifest_dir/plugin.json"
}

write_plugin_mcp_config() {
  local target="$1"
  cat > "$(out_path "$target")" <<'JSON'
{
  "mcpServers": {
    "cadre": {
      "command": "cadre-mcp",
      "args": [],
      "cwd": "."
    }
  }
}
JSON
}

write_plugin_mcp_config_for_platform() {
  local platform="$1" plugin_dir="$2"
  case "$platform" in
    codex) write_plugin_mcp_config "$plugin_dir/.mcp.json" ;;
    claude) write_plugin_mcp_config "$plugin_dir/mcp-config.json" ;;
  esac
}

write_plugin_readme() {
  local plugin_dir="$1" platform="$2"
  cat > "$(out_path "$plugin_dir/README.md")" <<EOF
<!-- $PLUGIN_MARKER -->

# Cadre $platform Plugin

This generated plugin packages the Cadre skill, workflow protocols, MCP-served
references and template inventory, and MCP server for $platform. Edit the master
workflow sources under \`skills/cadre/protocols/\`, reference masters under
\`scripts/agent-refs/\`, templates under \`templates/\`, and runtime TypeScript
under \`src/\`, then run:

\`\`\`bash
pnpm generate
\`\`\`

The LSP setup and review helpers are bundled under \`scripts/\` so Cadre
workflows can copy or invoke them. They are not auto-registered as plugin LSP
servers because Cadre configures per-project language servers in
\`cadre/lsp.json\`.

Cadre MCP is a required runtime. Use \`cadre_project\` with
\`{"action":"ping"}\` to verify the server is available. All project-scoped MCP
tools require a per-call \`root\` argument.
The server normalizes that path by walking upward to the nearest directory
containing \`cadre/\`, so callers may pass either the project root or a path
inside it. Use \`cadre_project\` with \`{"action":"root"}\` and \`root\` to
inspect the resolved project root.
EOF
}

write_marketplace_json() {
  local platform="$1" target="$2" source_path="$3"
  case "$platform" in
    codex)
      cat > "$target" <<JSON
{
  "name": "$PLUGIN_NAME",
  "interface": {
    "displayName": "Cadre"
  },
  "plugins": [
    {
      "name": "$PLUGIN_NAME",
      "source": {
        "source": "local",
        "path": "$source_path"
      },
      "policy": {
        "installation": "AVAILABLE",
        "authentication": "ON_INSTALL"
      },
      "category": "Productivity"
    }
  ]
}
JSON
      ;;
    claude)
      cat > "$target" <<JSON
{
  "name": "$PLUGIN_NAME",
  "owner": {
    "name": "$PLUGIN_AUTHOR_NAME"
  },
  "description": "Cadre skill-first workflows for Claude Code.",
  "plugins": [
    {
      "name": "$PLUGIN_NAME",
      "source": "$source_path",
      "description": "$PLUGIN_DESCRIPTION",
      "version": "$PLUGIN_VERSION",
      "author": {
        "name": "$PLUGIN_AUTHOR_NAME"
      },
      "category": "productivity",
      "tags": [
        "cadre",
        "skills",
        "mcp",
        "context-driven-development"
      ]
    }
  ]
}
JSON
      ;;
  esac
}

validate_generated_plugins() {
  CADRE_VALIDATE_ROOT="${GEN_ROOT:-$REPO_ROOT}" CADRE_VALIDATE_REPO_ROOT="${GEN_ROOT:+$GEN_ROOT/root}" node <<'NODE'
const fs = require("node:fs");
const path = require("node:path");

const root = process.env.CADRE_VALIDATE_ROOT || process.cwd();
const repoRoot = process.env.CADRE_VALIDATE_REPO_ROOT || path.resolve(root, "..");
const checks = [
  ["plugins/cadre/.codex-plugin/plugin.json", ["name", "version", "skills", "mcpServers"]],
  ["plugins/cadre/.mcp.json", ["mcpServers"]],
  ["plugins/cadre-claude/.claude-plugin/plugin.json", ["name", "version", "skills", "mcpServers"]],
  ["plugins/cadre-claude/mcp-config.json", ["mcpServers"]],
];

for (const [rel, keys] of checks) {
  const file = path.join(root, rel);
  if (!fs.existsSync(file)) throw new Error(`missing ${rel}`);
  const json = JSON.parse(fs.readFileSync(file, "utf8"));
  for (const key of keys) {
    if (!(key in json)) throw new Error(`${rel} missing ${key}`);
  }
}

const codexManifest = JSON.parse(fs.readFileSync(path.join(root, "plugins/cadre/.codex-plugin/plugin.json"), "utf8"));
if (codexManifest.skills !== "./skills/") throw new Error("Codex plugin manifest has wrong skills path");
if (codexManifest.mcpServers !== "./.mcp.json") throw new Error("Codex plugin manifest has wrong MCP path");
const codexMcp = JSON.parse(fs.readFileSync(path.join(root, "plugins/cadre/.mcp.json"), "utf8"));
if (codexMcp.mcpServers?.cadre?.command !== "cadre-mcp" || codexMcp.mcpServers?.cadre?.args?.length !== 0) {
  throw new Error("Codex MCP config must point at global cadre-mcp");
}
const claudeManifest = JSON.parse(fs.readFileSync(path.join(root, "plugins/cadre-claude/.claude-plugin/plugin.json"), "utf8"));
if (claudeManifest.skills !== "./skills/") throw new Error("Claude plugin manifest has wrong skills path");
if (claudeManifest.mcpServers !== "./mcp-config.json") throw new Error("Claude plugin manifest has wrong MCP path");
const claudeMcp = JSON.parse(fs.readFileSync(path.join(root, "plugins/cadre-claude/mcp-config.json"), "utf8"));
if (claudeMcp.mcpServers?.cadre?.command !== "cadre-mcp" || claudeMcp.mcpServers?.cadre?.args?.length !== 0) {
  throw new Error("Claude MCP config must point at global cadre-mcp");
}
for (const field of ["name", "version", "description", "homepage", "repository", "license"]) {
  if (codexManifest[field] !== claudeManifest[field]) {
    throw new Error(`Plugin manifests diverged on ${field}`);
  }
}
if (JSON.stringify(codexManifest.keywords) !== JSON.stringify(claudeManifest.keywords)) {
  throw new Error("Plugin manifests diverged on keywords");
}
if (codexManifest.author?.name !== claudeManifest.author?.name) {
  throw new Error("Plugin manifests diverged on author name");
}
if (codexManifest.interface?.displayName !== "Cadre") {
  throw new Error("Codex plugin manifest missing interface display name");
}
if (!codexManifest.interface || "agents" in codexManifest) {
  throw new Error("Codex plugin manifest contains Claude-only fields");
}
if (!claudeManifest.displayName || claudeManifest.displayName !== "Cadre") {
  throw new Error("Claude plugin manifest missing display name");
}
if ("agents" in claudeManifest) {
  throw new Error("Claude plugin manifest should not declare generated agents");
}
for (const text of [JSON.stringify(codexMcp), JSON.stringify(claudeMcp)]) {
  if (text.includes("${PLUGIN_ROOT}") || text.includes("${CLAUDE_PLUGIN_ROOT}")) {
    throw new Error("Generated MCP config still contains placeholder paths");
  }
}

const harnessCodexMarketplace = JSON.parse(fs.readFileSync(path.join(root, ".agents/plugins/marketplace.json"), "utf8"));
if (harnessCodexMarketplace.plugins?.[0]?.source?.path !== "./plugins/cadre") {
  throw new Error("Harness Codex marketplace has wrong plugin path");
}
const harnessClaudeMarketplace = JSON.parse(fs.readFileSync(path.join(root, ".claude-plugin/marketplace.json"), "utf8"));
if (harnessClaudeMarketplace.plugins?.[0]?.source !== "./plugins/cadre-claude") {
  throw new Error("Harness Claude marketplace has wrong plugin path");
}
const rootCodexMarketplace = JSON.parse(fs.readFileSync(path.join(repoRoot, ".agents/plugins/marketplace.json"), "utf8"));
if (rootCodexMarketplace.plugins?.[0]?.source?.path !== "./harness/plugins/cadre") {
  throw new Error("Root Codex marketplace has wrong plugin path");
}
const rootClaudeMarketplace = JSON.parse(fs.readFileSync(path.join(repoRoot, ".claude-plugin/marketplace.json"), "utf8"));
if (rootClaudeMarketplace.plugins?.[0]?.source !== "./harness/plugins/cadre-claude") {
  throw new Error("Root Claude marketplace has wrong plugin path");
}

for (const rel of [
  "plugins/cadre/skills/cadre/SKILL.md",
  "plugins/cadre-claude/skills/cadre/SKILL.md",
]) {
  if (!fs.existsSync(path.join(root, rel))) throw new Error(`missing ${rel}`);
}
for (const rel of [
  "plugins/cadre/README.md",
  "plugins/cadre/assets",
  "plugins/cadre/references",
  "plugins/cadre/templates",
  "plugins/cadre/agents",
  "plugins/cadre/scripts",
  "plugins/cadre/scripts/cadre-core.js",
  "plugins/cadre/scripts/cadre-job-runner.js",
  "plugins/cadre/scripts/cadre-lsp-setup.js",
  "plugins/cadre/scripts/cadre-lsp-review.js",
  "plugins/cadre/scripts/cadre-lsp-daemon.js",
  "plugins/cadre/skills/cadre/skill.json",
  "plugins/cadre/skills/cadre/protocols",
  "plugins/cadre-claude/README.md",
  "plugins/cadre-claude/assets",
  "plugins/cadre-claude/references",
  "plugins/cadre-claude/templates",
  "plugins/cadre-claude/agents",
  "plugins/cadre-claude/scripts",
  "plugins/cadre-claude/scripts/cadre-core.js",
  "plugins/cadre-claude/scripts/cadre-job-runner.js",
  "plugins/cadre-claude/scripts/cadre-lsp-setup.js",
  "plugins/cadre-claude/scripts/cadre-lsp-review.js",
  "plugins/cadre-claude/scripts/cadre-lsp-daemon.js",
  "plugins/cadre-claude/skills/cadre/skill.json",
  "plugins/cadre-claude/skills/cadre/protocols",
]) {
  if (fs.existsSync(path.join(root, rel))) throw new Error(`unexpected generated file: ${rel}`);
}
NODE
}

write_marketplaces() {
  mkdir -p "$(dirname "$(out_path "$CODEX_PLUGIN_MARKETPLACE")")"
  write_marketplace_json "codex" "$(out_path "$CODEX_PLUGIN_MARKETPLACE")" "./plugins/cadre"
  mkdir -p "$(dirname "$(out_path "$CLAUDE_PLUGIN_MARKETPLACE")")"
  write_marketplace_json "claude" "$(out_path "$CLAUDE_PLUGIN_MARKETPLACE")" "./plugins/cadre-claude"
}

write_root_marketplaces() {
  mkdir -p "$(dirname "$(out_root_path "$ROOT_CODEX_PLUGIN_MARKETPLACE")")"
  write_marketplace_json "codex" "$(out_root_path "$ROOT_CODEX_PLUGIN_MARKETPLACE")" "./harness/plugins/cadre"
  mkdir -p "$(dirname "$(out_root_path "$ROOT_CLAUDE_PLUGIN_MARKETPLACE")")"
  write_marketplace_json "claude" "$(out_root_path "$ROOT_CLAUDE_PLUGIN_MARKETPLACE")" "./harness/plugins/cadre-claude"
}

generate_plugins() {
  rm -rf "$(out_path "$CODEX_PLUGIN_DIR")" "$(out_path "$CLAUDE_PLUGIN_DIR")"

  generate_plugin_bundle() {
    local skill_dir="$1" plugin_dir="$2"
    copy_skill_tree "$skill_dir" "$plugin_dir/skills/cadre"
  }

  generate_plugin_bundle "$CODEX_SKILL_DIR" "$CODEX_PLUGIN_DIR"
  generate_plugin_bundle "$CLAUDE_SKILL_DIR" "$CLAUDE_PLUGIN_DIR"

  write_plugin_manifest "codex" "$CODEX_PLUGIN_DIR"
  write_plugin_mcp_config_for_platform "codex" "$CODEX_PLUGIN_DIR"
  write_plugin_manifest "claude" "$CLAUDE_PLUGIN_DIR"
  write_plugin_mcp_config_for_platform "claude" "$CLAUDE_PLUGIN_DIR"
  write_marketplaces
  write_root_marketplaces
  validate_generated_plugins
}

main() {
  local ref count stale d f master pair src name

  if [[ ! -d "$SOURCE_PROTOCOL_DIR" ]]; then
    echo "error: missing $SOURCE_PROTOCOL_DIR/ directory" >&2
    exit 1
  fi
  if [[ ! -f "$SOURCE_SKILL_FILE" ]]; then
    echo "error: missing $SOURCE_SKILL_FILE" >&2
    exit 1
  fi
  if [[ ! -d "$TEMPLATES_SRC" ]]; then
    echo "error: missing $TEMPLATES_SRC/ directory" >&2
    exit 1
  fi
  if [[ ! -f "skills/cadre/skill.json" ]]; then
    echo "error: missing skills/cadre/skill.json" >&2
    exit 1
  fi
  for ref in "${JSON_REFS[@]}"; do
    if [[ ! -f "$ref" ]]; then
      echo "error: missing $ref" >&2
      exit 1
    fi
  done

  build_runtime

  generate_skill "$CLAUDE_SKILL_DIR"
  generate_skill "$CODEX_SKILL_DIR"
  generate_plugins

  count="$(ls "$SOURCE_PROTOCOL_DIR"/cadre-*.json | wc -l | tr -d ' ')"

  if [[ "$MODE" == "--check" ]]; then
    echo "✓ Generated plugin bundles can be produced from source."
    echo "  Checked thin Codex/Claude plugin manifests, MCP configs, and marketplaces."
  else
    echo "✓ Embedded $count workflow protocols into the Cadre MCP runtime."
    echo "  .claude/skills/cadre/ .agents/skills/cadre/ contain SKILL.md only"
    echo "  plugins/cadre-claude/ plugins/cadre/ are thin MCP entrypoints for global cadre-mcp"
  fi
}

main
