export const DEFAULT_STARTUP_TIMEOUT_MS = 10000;

export const DEFAULT_REQUEST_TIMEOUT_MS = 8000;

export const DEFAULT_SHUTDOWN_TIMEOUT_MS = 2000;

export const MAX_TEXT_REFERENCE_RESULTS = 50;

export const MAX_SCAN_FILE_BYTES = 1024 * 1024;
