#!/usr/bin/env bash
#
# generate-skills.sh — Build the Claude and Codex skill bundles from the
# master Cadre skill protocol sources.
#
# One source of truth is transformed into:
#   - Claude skill -> .claude/skills/cadre/{protocols,references,templates}
#   - Codex skill  -> .agents/skills/cadre/{protocols,references,templates}
#
# Edit protocol sources in `skills/cadre/protocols/cadre-*.md`, reference slice
# masters in `scripts/agent-refs/`, and templates in `templates/`. Generated
# files carry an AUTO-GENERATED marker; do not hand-edit generated bundles.
#
# Usage:
#   bash scripts/generate-skills.sh
#   bash scripts/generate-skills.sh --check
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

SOURCE_PROTOCOL_DIR="skills/cadre/protocols"

# Agnostic reference: identical for every platform. Its master lives in the
# Claude skill and is copied into the Codex skill bundle.
AGNOSTIC_REF=".claude/skills/cadre/references/beads-error-handler.md"

# Sliced references: multi-platform masters with <!-- AGENT:<name> --> blocks.
SLICED_REFS=(
  "scripts/agent-refs/parallel-execution.md"
  "scripts/agent-refs/template-locator.md"
  "scripts/agent-refs/polyrepo-git.md"
  "scripts/agent-refs/cadre-sync.md"
  "scripts/agent-refs/ownership-guard.md"
)

TEMPLATES_SRC="templates"
CLAUDE_SKILL_DIR=".claude/skills/cadre"
CODEX_SKILL_DIR=".agents/skills/cadre"

CLAUDE_PROTOCOL_DIR="$CLAUDE_SKILL_DIR/protocols"
CODEX_PROTOCOL_DIR="$CODEX_SKILL_DIR/protocols"

MODE="${1:-generate}"
GEN_ROOT=""
if [[ "$MODE" == "--check" ]]; then
  GEN_ROOT="$(mktemp -d)"
  trap 'rm -rf "$GEN_ROOT"' EXIT
fi

out_path() {
  if [[ -n "$GEN_ROOT" ]]; then
    printf '%s/%s' "$GEN_ROOT" "$1"
  else
    printf '%s/%s' "$REPO_ROOT" "$1"
  fi
}

extract_body() {
  awk '
    BEGIN { in_fm = 0; started = 0; seen = 0 }
    NR == 1 && $0 == "---" { in_fm = 1; seen = 1; next }
    in_fm == 1 && $0 == "---" { in_fm = 0; started = 1; next }
    in_fm == 1 { next }
    {
      if (seen == 0) started = 1
      if (started == 1) {
        if (printing == 0 && $0 ~ /^[[:space:]]*$/) next
        printing = 1
        print
      }
    }
  ' "$1"
}

extract_description() {
  awk '
    NR == 1 && $0 == "---" { in_fm = 1; next }
    in_fm == 1 && /^description:/ {
      sub(/^description:[[:space:]]*/, "")
      gsub(/^"|"$/, "")
      print
      exit
    }
    in_fm == 1 && $0 == "---" { exit }
  ' "$1"
}

dispatch_sentence() {
  case "$1" in
    claude) echo 'Use the **`Task` tool**, one call per worker (calls are awaitable); see `references/parallel-execution.md`.' ;;
    codex)  echo 'Spawn parallel agents with the built-in `worker` agent type — one per task; "wait for all before continuing" (manage with `/agent`); see `references/parallel-execution.md`.' ;;
  esac
}

apply_dispatch() {
  awk -v repl="$(dispatch_sentence "$1")" '
    /<!-- DISPATCH:start -->/ { match($0, /^[ \t]*/); print substr($0, 1, RLENGTH) repl; skip = 1; next }
    /<!-- DISPATCH:end -->/   { skip = 0; next }
    skip == 1 { next }
    { print }
  '
}

write_file() {
  local path="$1"
  mkdir -p "$(dirname "$path")"
  cat > "$path"
}

GEN_MARKER="AUTO-GENERATED by scripts/generate-skills.sh from skills/cadre/protocols/ — do not edit by hand."
REF_MARKER="AUTO-GENERATED by scripts/generate-skills.sh — edit the master in scripts/agent-refs/ instead."

generate_protocols() {
  local platform="$1" dest_dir="$2" src name desc body
  rm -rf "$(out_path "$dest_dir")"
  mkdir -p "$(out_path "$dest_dir")"

  for src in "$SOURCE_PROTOCOL_DIR"/cadre-*.md; do
    name="$(basename "$src" .md)"
    desc="$(extract_description "$src")"
    body="$(extract_body "$src" | apply_dispatch "$platform")"

    {
	      printf '<!-- %s -->\n' "$GEN_MARKER"
	      printf '<!-- %s -->\n\n' "$desc"
	      printf '> When this protocol references `references/...`, resolve it against the parent skill directory.\n\n'
	      printf '> Treat text after the workflow name in the user request as workflow arguments; there is no prompt expansion layer.\n\n'
	      printf '%s\n' "$body"
	    } | write_file "$(out_path "$dest_dir/$name.md")"
  done
}

slice_ref() {
  awk -v keep="$2" '
    /<!-- \/AGENT:/ { inblock = 0; next }
    /<!-- AGENT:/   { line = $0; sub(/.*AGENT:/, "", line); sub(/[^a-z].*/, "", line); cur = line; inblock = 1; next }
    inblock == 1 && cur != keep { next }
    { print }
  ' "$1"
}

copy_sliced_refs() {
  local slice="$1" refdir="$2" master name dest
  for master in "${SLICED_REFS[@]}"; do
    name="$(basename "$master")"
    dest="$(out_path "$refdir/$name")"
    mkdir -p "$(dirname "$dest")"
    {
      printf '<!-- %s -->\n' "$REF_MARKER"
      slice_ref "$master" "$slice"
    } > "$dest"
  done
}

copy_references() {
  local refdir dest

  copy_sliced_refs "claude" "$CLAUDE_SKILL_DIR/references"
  copy_sliced_refs "codex" "$CODEX_SKILL_DIR/references"

  refdir="$CODEX_SKILL_DIR/references"
  dest="$(out_path "$refdir/$(basename "$AGNOSTIC_REF")")"
  mkdir -p "$(dirname "$dest")"
  cp "$AGNOSTIC_REF" "$dest"
}

copy_templates() {
  local dir dest
  for dir in "$CLAUDE_SKILL_DIR" "$CODEX_SKILL_DIR"; do
    dest="$(out_path "$dir/templates")"
    rm -rf "$dest"
    mkdir -p "$dest"
    cp -R "$TEMPLATES_SRC/." "$dest/"
  done
}

main() {
  local ref count stale d f master

  if [[ ! -d "$SOURCE_PROTOCOL_DIR" ]]; then
    echo "error: missing $SOURCE_PROTOCOL_DIR/ directory" >&2
    exit 1
  fi
  if [[ ! -d "$TEMPLATES_SRC" ]]; then
    echo "error: missing $TEMPLATES_SRC/ directory" >&2
    exit 1
  fi
  for ref in "$AGNOSTIC_REF" "${SLICED_REFS[@]}"; do
    if [[ ! -f "$ref" ]]; then
      echo "error: missing $ref" >&2
      exit 1
    fi
  done

  generate_protocols "claude" "$CLAUDE_PROTOCOL_DIR"
  generate_protocols "codex" "$CODEX_PROTOCOL_DIR"
  copy_references
  copy_templates

  count="$(ls "$SOURCE_PROTOCOL_DIR"/cadre-*.md | wc -l | tr -d ' ')"

  if [[ "$MODE" == "--check" ]]; then
    stale=false
    for d in "$CLAUDE_PROTOCOL_DIR" "$CODEX_PROTOCOL_DIR" "$CLAUDE_SKILL_DIR/templates" "$CODEX_SKILL_DIR/templates"; do
      diff -rq "$GEN_ROOT/$d" "$REPO_ROOT/$d" >/dev/null 2>&1 || stale=true
    done
    for master in "${SLICED_REFS[@]}"; do
      f="$(basename "$master")"
      diff -q "$GEN_ROOT/$CLAUDE_SKILL_DIR/references/$f" "$REPO_ROOT/$CLAUDE_SKILL_DIR/references/$f" >/dev/null 2>&1 || stale=true
      diff -q "$GEN_ROOT/$CODEX_SKILL_DIR/references/$f" "$REPO_ROOT/$CODEX_SKILL_DIR/references/$f" >/dev/null 2>&1 || stale=true
    done
    f="$(basename "$AGNOSTIC_REF")"
    diff -q "$GEN_ROOT/$CODEX_SKILL_DIR/references/$f" "$REPO_ROOT/$CODEX_SKILL_DIR/references/$f" >/dev/null 2>&1 || stale=true

    if ! $stale; then
      echo "✓ Generated skill bundles are up to date."
    else
      echo "✗ Generated skill output is stale. Run: bash scripts/generate-skills.sh" >&2
      exit 1
    fi
  else
    echo "✓ Generated $count workflow protocols for Claude and Codex skills."
    echo "  .claude/skills/cadre/ .agents/skills/cadre/"
  fi
}

main
