#!/usr/bin/env bash
#
# generate-commands.sh — Derive every supported platform's command set from the
# canonical Claude Code commands in `.claude/commands/conductor-*.md`.
#
# One source of truth (the Claude `.md` commands) is transformed into:
#   - Codex CLI         -> .codex/prompts/conductor-*.md
#   - Cursor            -> .cursor/commands/conductor-*.md
#   - Antigravity CLI   -> .agent/workflows/conductor-*.md
#   - GitHub Copilot    -> .github/prompts/conductor-*.prompt.md
#
# Each Claude command file has YAML frontmatter (`description:`, optional
# `argument-hint:`) followed by a Markdown body. The body uses the `$ARGUMENTS`
# placeholder and references `references/beads-error-handler.md`. This script
# adapts the frontmatter and argument placeholder to each platform's
# conventions and copies the shared reference file alongside the commands so
# every output directory is self-contained.
#
# Re-run after editing any `.claude/commands/conductor-*.md` to keep all
# platforms in sync. Generated files carry an "AUTO-GENERATED" marker; do not
# hand-edit them — edit the canonical Claude command and regenerate.
#
# Usage:
#   bash scripts/generate-commands.sh            # generate all platforms
#   bash scripts/generate-commands.sh --check    # fail if output is stale (CI)
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

SRC_DIR=".claude/commands"
# Reference files that command bodies link to (path `references/<name>`); each is
# copied into every platform's references/ dir so the link resolves locally.
REF_SRCS=(
  ".claude/skills/conductor/references/beads-error-handler.md"
  ".claude/skills/conductor/references/template-locator.md"
  ".claude/skills/conductor/references/parallel-execution.md"
)
TEMPLATES_SRC="templates"                  # canonical templates (single source)
SKILL_DIR=".claude/skills/conductor"       # Claude skill; templates bundled here

CODEX_DIR=".codex/prompts"
CURSOR_DIR=".cursor/commands"
ANTIGRAVITY_DIR=".agent/workflows"
COPILOT_DIR=".github/prompts"

# Phrase substituted for the literal `$ARGUMENTS` placeholder on platforms that
# do not perform `$ARGUMENTS` expansion (Cursor, Antigravity, Copilot). On these
# platforms any text typed after the slash command is appended to the prompt, so
# we describe that instead of using a token that would survive verbatim.
ARGS_PHRASE="the input provided with this command (the text typed after the command name)"

MODE="${1:-generate}"
GEN_ROOT=""
if [[ "$MODE" == "--check" ]]; then
  GEN_ROOT="$(mktemp -d)"
  trap 'rm -rf "$GEN_ROOT"' EXIT
fi

# out_path <relative-output-path> -> absolute path under repo (or temp in --check)
out_path() {
  if [[ -n "$GEN_ROOT" ]]; then
    printf '%s/%s' "$GEN_ROOT" "$1"
  else
    printf '%s/%s' "$REPO_ROOT" "$1"
  fi
}

# Extract the Markdown body (everything after the YAML frontmatter block).
# If the file has no leading `---`, the whole file is the body.
extract_body() {
  awk '
    BEGIN { in_fm = 0; started = 0; seen = 0 }
    NR == 1 && $0 == "---" { in_fm = 1; seen = 1; next }
    in_fm == 1 && $0 == "---" { in_fm = 0; started = 1; next }
    in_fm == 1 { next }
    {
      if (seen == 0) started = 1     # no frontmatter: print from line 1
      if (started == 1) {
        if (printing == 0 && $0 ~ /^[[:space:]]*$/) next  # trim leading blanks
        printing = 1
        print
      }
    }
  ' "$1"
}

# Extract the `description:` value from the frontmatter.
extract_description() {
  awk '
    NR == 1 && $0 == "---" { in_fm = 1; next }
    in_fm == 1 && /^description:/ {
      sub(/^description:[[:space:]]*/, "")
      gsub(/^"|"$/, "")
      print
      exit
    }
    in_fm == 1 && $0 == "---" { exit }
  ' "$1"
}

GEN_MARKER="AUTO-GENERATED by scripts/generate-commands.sh from .claude/commands/ — do not edit by hand."

write_file() {
  local path="$1"
  mkdir -p "$(dirname "$path")"
  cat > "$path"
}

generate_platform() {
  local platform="$1" src name desc body
  for src in "$SRC_DIR"/conductor-*.md; do
    name="$(basename "$src" .md)"            # e.g. conductor-setup
    desc="$(extract_description "$src")"
    body="$(extract_body "$src")"

    case "$platform" in
      codex)
        # Codex CLI expands `$ARGUMENTS` natively; keep it. No frontmatter —
        # Codex treats the whole markdown file as the prompt body.
        {
          printf '<!-- %s -->\n' "$GEN_MARKER"
          printf '<!-- %s -->\n\n' "$desc"
          printf '%s\n' "$body"
        } | write_file "$(out_path "$CODEX_DIR/$name.md")"
        ;;
      cursor)
        # Cursor commands are plain Markdown with no frontmatter.
        {
          printf '<!-- %s -->\n\n' "$GEN_MARKER"
          printf '%s\n' "$body"
        } | sed "s|\$ARGUMENTS|$ARGS_PHRASE|g" \
          | write_file "$(out_path "$CURSOR_DIR/$name.md")"
        ;;
      antigravity)
        # Antigravity workflows require YAML frontmatter with a description.
        {
          printf -- '---\n'
          printf 'description: %s\n' "$desc"
          printf -- '---\n\n'
          printf '<!-- %s -->\n\n' "$GEN_MARKER"
          printf '%s\n' "$body"
        } | sed "s|\$ARGUMENTS|$ARGS_PHRASE|g" \
          | write_file "$(out_path "$ANTIGRAVITY_DIR/$name.md")"
        ;;
      copilot)
        # GitHub Copilot prompt files: `.prompt.md` with YAML frontmatter.
        {
          printf -- '---\n'
          printf 'description: %s\n' "$desc"
          printf 'agent: agent\n'
          printf -- '---\n\n'
          printf '<!-- %s -->\n\n' "$GEN_MARKER"
          printf '%s\n' "$body"
        } | sed "s|\$ARGUMENTS|$ARGS_PHRASE|g" \
          | write_file "$(out_path "$COPILOT_DIR/$name.prompt.md")"
        ;;
    esac
  done
}

# Copy the shared reference files into each platform dir under references/ so the
# `references/<name>` links in command bodies resolve locally.
copy_reference() {
  local dir ref dest
  for dir in "$CODEX_DIR" "$CURSOR_DIR" "$ANTIGRAVITY_DIR" "$COPILOT_DIR"; do
    for ref in "${REF_SRCS[@]}"; do
      dest="$(out_path "$dir/references/$(basename "$ref")")"
      mkdir -p "$(dirname "$dest")"
      cp "$ref" "$dest"
    done
  done
}

# Bundle the canonical templates/ directory (workflow.md, code_styleguides/, …)
# with every command set so `conductor-setup` can find them after install. It is
# copied into each platform's command dir and into the Claude skill, matching the
# install locations that `conductor-setup`'s template-discovery step probes.
copy_templates() {
  local dir dest
  for dir in "$CODEX_DIR" "$CURSOR_DIR" "$ANTIGRAVITY_DIR" "$COPILOT_DIR" "$SKILL_DIR"; do
    dest="$(out_path "$dir/templates")"
    rm -rf "$dest"
    mkdir -p "$dest"
    cp -R "$TEMPLATES_SRC/." "$dest/"
  done
}

main() {
  local ref
  for ref in "${REF_SRCS[@]}"; do
    if [[ ! -f "$ref" ]]; then
      echo "error: missing $ref" >&2
      exit 1
    fi
  done
  if [[ ! -d "$TEMPLATES_SRC" ]]; then
    echo "error: missing $TEMPLATES_SRC/ directory" >&2
    exit 1
  fi

  for platform in codex cursor antigravity copilot; do
    generate_platform "$platform"
  done
  copy_reference
  copy_templates

  local count
  count="$(ls "$SRC_DIR"/conductor-*.md | wc -l | tr -d ' ')"

  if [[ "$MODE" == "--check" ]]; then
    if diff -rq "$GEN_ROOT/$CODEX_DIR" "$REPO_ROOT/$CODEX_DIR" >/dev/null 2>&1 \
       && diff -rq "$GEN_ROOT/$CURSOR_DIR" "$REPO_ROOT/$CURSOR_DIR" >/dev/null 2>&1 \
       && diff -rq "$GEN_ROOT/$ANTIGRAVITY_DIR" "$REPO_ROOT/$ANTIGRAVITY_DIR" >/dev/null 2>&1 \
       && diff -rq "$GEN_ROOT/$COPILOT_DIR" "$REPO_ROOT/$COPILOT_DIR" >/dev/null 2>&1 \
       && diff -rq "$GEN_ROOT/$SKILL_DIR/templates" "$REPO_ROOT/$SKILL_DIR/templates" >/dev/null 2>&1; then
      echo "✓ Generated commands and bundled templates are up to date."
    else
      echo "✗ Generated output is stale. Run: bash scripts/generate-commands.sh" >&2
      exit 1
    fi
  else
    echo "✓ Generated $count commands each for: Codex, Cursor, Antigravity, GitHub Copilot."
    echo "  Bundled references/ and templates/ into every command set + the Claude skill."
    echo "  .codex/prompts/ .cursor/commands/ .agent/workflows/ .github/prompts/ .claude/skills/conductor/templates/"
  fi
}

main
